#!/bin/bash

## dotfiles install script

# The script doesn't overwrite existing config options. It prefers
# symlinking to the dotfiles dir, but if a file already exists then it
# appends a 'source' command to it.

# Defaults
source_dir=$(pwd)
target_dir=$HOME
to_install="bashrc screenrc Xdefaults Xresources vimrc"

# Functions
install_dotfile () {
    local source_file="$1"
    local target_file="$target_dir/.$source_file"

    # If the file doesn't exist, make a symlink
    if [[ ! -e "$target_file" ]]; then
        echo "$target_file doesn't exist, symlinking to $source_file"
        ln -s "$file" "$target_dir/.$file"
    # If the target is a symlink to our file, do nothing
    elif [[ "$source_dir/$source_file" == "$HOME/$(ls -l "$target_file" | awk '{print $11}')" ]]; then
        echo "$target_file is already symlinked to $source_file"
    # Else source the new file at the end of the old one 
    else
        echo "$target_file exist, appending \"source $source_file\" to its end"
        echo -e "\n\nsource $source_dir/$source_file" >> "$target_file"
    fi
}

# Main logic
for file in $to_install; do
    install_dotfile "$file"
done
